-- Create pages table for note manager
CREATE TABLE IF NOT EXISTS pages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL DEFAULT 'Untitled',
    content TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_updated_at (updated_at DESC)
);

-- Insert some sample pages with Markdown content
INSERT INTO pages (title, content) VALUES
('Bienvenue', '# Bienvenue dans Note Manager ! 👋\n\nCeci est votre première note. Note Manager supporte le **Markdown** pour formater vos notes de manière élégante.\n\n## Qu''est-ce que Markdown ?\n\nMarkdown est un langage de balisage léger qui vous permet de formater du texte en utilisant une syntaxe simple.\n\n### Avantages\n\n- ✅ **Facile à lire** et à écrire\n- ✅ Compatible avec de nombreux outils\n- ✅ Permet de créer des documents structurés\n- ✅ Convertible en HTML\n\n> *Astuce :* Cliquez sur le bouton **Preview** pour voir le rendu de votre Markdown !\n\n---\n\nN''hésitez pas à modifier cette note ou à en créer de nouvelles.'),

('Guide Markdown', '# Guide de Syntaxe Markdown\n\nCe guide vous montre les principales fonctionnalités Markdown supportées.\n\n## Formatage de Texte\n\nVous pouvez formater le texte de différentes manières :\n\n- **Texte en gras** avec `**texte**`\n- *Texte en italique* avec `*texte*`\n- `Code inline` avec des backticks\n- ~~Texte barré~~ avec `~~texte~~`\n\n## Titres\n\nUtilisez # pour créer des titres de différents niveaux :\n\n```markdown\n# Titre niveau 1\n## Titre niveau 2\n### Titre niveau 3\n```\n\n## Listes\n\n### Liste à puces\n\n- Premier élément\n- Deuxième élément\n  - Sous-élément A\n  - Sous-élément B\n- Troisième élément\n\n### Liste numérotée\n\n1. Première étape\n2. Deuxième étape\n3. Troisième étape\n\n## Citations\n\n> Les citations sont créées avec le symbole >\n>\n> Vous pouvez avoir plusieurs lignes dans une citation.\n\n## Code\n\n### Code inline\n\nUtilisez `console.log()` pour afficher dans la console.\n\n### Blocs de code\n\n```javascript\nfunction hello(name) {\n  console.log(`Bonjour ${name} !`);\n}\n\nhello(\"Monde\");\n```\n\n## Liens et Images\n\n[Visitez GitHub](https://github.com)\n\n![Logo Markdown](https://markdown-here.com/img/icon256.png)\n\n## Tableaux\n\n| Fonctionnalité | Support | Description |\n|----------------|---------|-------------|\n| Titres         | ✅      | H1 à H6     |\n| Listes         | ✅      | À puces et numérotées |\n| Code           | ✅      | Inline et blocs |\n| Tableaux       | ✅      | Complets    |\n\n---\n\n**Bon usage de Markdown ! 🎉**'),

('To-Do List', '# 📋 To-Do Liste - Projet Web\n\n## Phase 1 : Conception\n\n- [x] Définir les fonctionnalités principales\n- [x] Créer les maquettes UI/UX\n- [x] Choisir la stack technique\n- [ ] Valider avec l''équipe\n\n## Phase 2 : Développement\n\n### Backend\n\n- [x] Configuration de la base de données\n- [x] API REST pour les notes\n- [x] Gestion des erreurs\n- [ ] Tests unitaires\n\n### Frontend\n\n- [x] Interface utilisateur\n- [x] Support Markdown\n- [x] Mode Preview\n- [ ] Mode sombre\n- [ ] Recherche de notes\n\n## Phase 3 : Déploiement\n\n- [x] Configuration Docker\n- [x] Configuration Kubernetes\n- [ ] CI/CD Pipeline\n- [ ] Documentation utilisateur\n\n---\n\n## Notes Importantes\n\n> ⚠️ **Attention :** Tester toutes les fonctionnalités avant le déploiement en production.\n\n## Ressources Utiles\n\n- [Documentation Express](https://expressjs.com/)\n- [Guide Markdown](https://www.markdownguide.org/)\n- [Documentation Kubernetes](https://kubernetes.io/docs/)\n\n**Dernière mise à jour :** 2025-10-10'),

('Documentation', '# 📚 Documentation API - Note Manager\n\n## Vue d''ensemble\n\nNote Manager expose une API REST pour gérer vos notes.\n\n## Base URL\n\n```\nhttp://localhost:3000/api\n```\n\n## Endpoints\n\n### 1. Récupérer toutes les pages\n\n**GET** `/pages`\n\n**Réponse :**\n\n```json\n[\n  {\n    \"id\": 1,\n    \"title\": \"Ma note\",\n    \"updated_at\": \"2025-10-10T12:00:00Z\"\n  }\n]\n```\n\n### 2. Récupérer une page spécifique\n\n**GET** `/pages/:id`\n\n**Paramètres :**\n\n| Paramètre | Type | Description |\n|-----------|------|-------------|\n| id        | int  | ID de la page |\n\n**Réponse :**\n\n```json\n{\n  \"id\": 1,\n  \"title\": \"Ma note\",\n  \"content\": \"Contenu en Markdown\",\n  \"created_at\": \"2025-10-10T10:00:00Z\",\n  \"updated_at\": \"2025-10-10T12:00:00Z\"\n}\n```\n\n### 3. Créer une nouvelle page\n\n**POST** `/pages`\n\n**Body :**\n\n```json\n{\n  \"title\": \"Nouvelle note\",\n  \"content\": \"# Contenu\"\n}\n```\n\n### 4. Mettre à jour une page\n\n**PUT** `/pages/:id`\n\n**Body :**\n\n```json\n{\n  \"title\": \"Titre mis à jour\",\n  \"content\": \"Nouveau contenu\"\n}\n```\n\n### 5. Supprimer une page\n\n**DELETE** `/pages/:id`\n\n---\n\n## Codes de Statut HTTP\n\n| Code | Signification |\n|------|---------------|\n| 200  | Succès |\n| 201  | Créé |\n| 404  | Non trouvé |\n| 500  | Erreur serveur |\n\n## Exemple d''utilisation avec cURL\n\n```bash\n# Récupérer toutes les pages\ncurl http://localhost:3000/api/pages\n\n# Créer une nouvelle page\ncurl -X POST http://localhost:3000/api/pages \\\n  -H \"Content-Type: application/json\" \\\n  -d ''{"title":"Test","content":"# Hello"}'';\n```\n');
